#cloud-config
package_update: true
package_upgrade: true

packages:
  - gnupg
  - curl

write_files:
  - path: /home/ubuntu/mongodbuser.txt
    permissions: '0644'
    owner: ubuntu:ubuntu
    content: |
      use admin
      db.createUser({
        user: "admin",
        pwd: "Thomas-Password",
        roles: [ { role: "userAdminAnyDatabase", db: "admin" },
                 { role: "readWriteAnyDatabase",  db: "admin" },
                 { role: "dbAdminAnyDatabase",    db: "admin" } ]
      })

runcmd:
  - curl -fsSL https://pgp.mongodb.com/server-7.0.asc | gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
  - echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list
  - apt-get update -y
  - apt-get install -y mongodb-org
  - systemctl enable mongod
  - systemctl start mongod
  - sleep 10
  - sudo mongosh < /home/ubuntu/mongodbuser.txt
  - "sed -i 's|  bindIp: 127.0.0.1|  bindIp: 0.0.0.0|' /etc/mongod.conf"
  - "sed -i 's|#security:|security:\\n  authorization: enabled|' /etc/mongod.conf"
  - systemctl restart mongod
