#cloud-config
# KN-R-01: Redis (Key-Value-Datenbank) als Docker-Image auf einer AWS-Instanz.
# Installiert Docker und startet Redis 7 mit Passwort-Auth und Persistenz
# (appendonly), erreichbar auf Port 6379.
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCPIIO8uY8oWIihDv0tCAbX6toyG1RYkaLZyfGD1L+I07K4CnwAVBSU+81vw3Yv5sN9tj2Ccve9kzEeCNMld2mDP/Tt7edkx2MCToVfVx+njqwY/XbMY9bfdRKJLhIoLavuVNLnnkSIXdtlGr3JF71hPHzBDMEo64ofPCQ8hPsGxL1u3efb12jcWcRhudKtv7Qh6cVE47Zj4xImfi6VlLqwzcKZ5oCqR/z1hLLL+/pS3eM5Qsor5wmAqNfH4+z5eE+pOkFm7a0Nkygv9jwXIqtJzFGKYDe6ciBD04pEovdvY0FTyiv2vksQOVgjtu2faG2Iv1HOG0JktCIwJ49OEgjT teacher
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKCuWX/W66sjjNiDNuPpKgYO1xFqDoMJoeo5hz2LDNrF teacher-wir
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBDu2TqKRTR5fQ3n+p7ch7THeGjPEDyK8vl3mUKkBUZqSl3b7sMSTwB8gClMLGu5Y++9PjWpbrH+x4HjaqEHj6CbseBIhkRioZI3A4d8GzbYWtYCtViDy+8mXL5nub5QM3o9cohhRXHooWxP7J3QDuw45wEIK5VlfYSN4dwTiCkl/l6b/jTOhPWqT9sNvrMAvsIfwD6QHLtRO7EcHNuBqk8fRlEsfJYMBeuBA3qvyQIpnLzkw3r6rQgnXQuztJFXLPAn3RKvvRHh/vu4Rfov8bAOjHT+MGBVTcGI72zxLGXMiRd5UkkH0UPaiJWrJCYUHbM0qmuSvYT/qcsI/u+N4r Thomas
ssh_pwauth: true
disable_root: false
package_update: true
packages:
  - docker.io
runcmd:
  - sudo systemctl enable docker
  - sudo systemctl start docker
  - sudo docker run -d --name redis --restart unless-stopped -p 6379:6379 redis:7 redis-server --requirepass "Thomas-Password" --appendonly yes
